#!/usr/bin/env python3
"""Create a lightweight Llama-3.1 config compatibility model directory.

The torch251 environment currently uses transformers 4.37.x, which rejects the
newer Llama-3.1 rope_scaling schema. For these BEAT baseline sweeps the max
context is <= 1024, so we can use a symlinked model directory with the same
weights/tokenizer and a short-context-compatible config that removes the
Llama-3.1 long-context rope_scaling metadata.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def replace_symlink(src: Path, dst: Path) -> None:
    if dst.is_symlink() and Path(os.readlink(dst)) == src:
        return
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    dst.symlink_to(src)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--dest", required=True, type=Path)
    parser.add_argument(
        "--mode",
        choices=["remove_rope_scaling"],
        default="remove_rope_scaling",
        help="Compatibility transform to apply to config.json.",
    )
    args = parser.parse_args()

    source = args.source.resolve()
    dest = args.dest.resolve()
    if not source.is_dir():
        raise SystemExit(f"source model directory does not exist: {source}")
    config_path = source / "config.json"
    if not config_path.is_file():
        raise SystemExit(f"source model config missing: {config_path}")

    dest.mkdir(parents=True, exist_ok=True)

    config = json.loads(config_path.read_text())
    original_rope_scaling = config.pop("rope_scaling", None)
    config["max_position_embeddings"] = min(
        int(config.get("max_position_embeddings", 8192)),
        int(config.get("original_max_position_embeddings", 8192))
        if "original_max_position_embeddings" in config
        else 8192,
    )
    config["transformers_version_compat_note"] = (
        "Generated by prepare_llama3_compat_model.py for transformers 4.37.x. "
        "Weights/tokenizer are symlinked from the source model. Removed "
        "Llama-3.1 rope_scaling metadata for short-context BEAT sweeps."
    )

    (dest / "config.json").write_text(json.dumps(config, indent=2) + "\n")
    note = {
        "source": str(source),
        "mode": args.mode,
        "original_rope_scaling": original_rope_scaling,
        "compat_assumption": "BEAT official baseline sweep uses <=1024-token contexts.",
    }
    (dest / "compat_config_note.json").write_text(json.dumps(note, indent=2) + "\n")

    for item in source.iterdir():
        if item.name == "config.json":
            continue
        target = dest / item.name
        if item.is_dir():
            continue
        replace_symlink(item.resolve(), target)

    print(dest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
